spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5000}/customerdb
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  Jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 3001

logging:
  level:
    root: info

grpc:
  server:
    port: 9090

proto:
  service:
    address: ${ACCOUNT_SERVICE_HOST:localhost}
    grpc:
      port: 9091

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans



