spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5002}/paymentdb
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

kafka:
  topic:
    payment-processed: payment-processed

server:
  port: 3003

grpc:
  server:
    port: 9092

# Address of account-service gRPC server
proto:
  account:
    address: ${ACCOUNT_SERVICE_HOST:localhost}
    grpc:
      port: 9091

logging:
  level:
    root: info


